# Generated by Django 4.0.2 on 2022-02-24 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Eduaction',
            new_name='Education',
        ),
    ]
