# Generated by Django 4.0.2 on 2022-02-25 11:05

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_about_email_alter_certification_certi_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=10, region=None, unique=True),
        ),
    ]
