# Generated by Django 4.0.2 on 2022-02-25 11:09

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_about_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=13, region=None, unique=True),
        ),
    ]
