# Generated by Django 4.0.2 on 2022-02-27 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_education_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
    ]
