# Generated by Django 4.0.2 on 2022-02-28 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_education_end_date_alter_education_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='currently_working',
            field=models.BooleanField(default=False),
        ),
    ]
