# Generated by Django 4.0.2 on 2022-02-28 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_project_currently_working'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certification',
            old_name='certi_name',
            new_name='certificate_name',
        ),
    ]
