# Generated by Django 4.0.2 on 2022-02-28 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_certi_name_certification_certificate_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='proj_github_link',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
