# Generated by Django 4.0.2 on 2022-02-28 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_project_proj_github_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('Programming Languages', 'Programming Languages'), ('Frameworks', 'Frameworks'), ('Frontend Technology', 'Frontend Technology'), ('Database Technology', 'Database Technology'), ('Source Control', 'Source Control')], max_length=50),
        ),
    ]
